# Bemorga dori tavsiya qilish tizimi

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

Datasetni yuklab olamiz

In [3]:
df = pd.read_csv("../data/raw/drug200.csv")
df.head()

   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  drugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  drugY

Matinli ustunlarga ishlov beramiz

In [6]:
encoder = LabelEncoder()
df['Sex'] = encoder.fit_transform(df['Sex'].values)
df['BP'] = encoder.fit_transform(df['BP'].values)
df['Cholesterol'] = encoder.fit_transform(df['Cholesterol'].values)

In [7]:
df.sample(10)

     Age  Sex  BP  Cholesterol  Na_to_K   Drug
71    28    0   2            0   19.675  drugY
159   34    0   1            1   12.923  drugX
58    60    1   2            1   10.091  drugX
32    49    1   1            1   11.014  drugX
101   45    0   0            0   12.854  drugA
119   61    0   0            0   25.475  drugY
6     49    0   2            0   16.275  drugY
102   28    0   1            0   13.127  drugC
182   20    0   1            1   11.686  drugX
155   49    1   1            0   10.537  drugC

In [ ]:
df.to_csv("../data/processed/drug200_transformed.csv", index=Fald)